# reshape

In [101]:
import numpy as np
x = np.arange(20)

In [102]:
# x를 (4,5) 2차원 배열로 리턴
y_2 = x.reshape(4, 5)
print(y_2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [103]:
# x를 (4,5) 3차원 배열로 리턴
y_3 = x.reshape(2,2,5)
print(y_3)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


## reshape이 -1인 경우

In [104]:
import numpy as np
x = np.arange(20)
y = x.reshape(4, -1)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [105]:
# 3차원
y = x.reshape(2,5, -1)
print(y)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


### for 구문으로 만들어보기

In [106]:
org =[[ 0,  1,  2,  3,  4], [ 5,  6  ,7,  8 , 9], [10 ,11 ,12 ,13 ,14], [15 ,16, 17 ,18, 19]]

org_1=[]
for i in range(len(org)):
  for j in range(len(org[i])) :
    org_1.append(org[i][j])
print(org_1)    

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [140]:
org =[[ 0,  1,  2,  3,  4], [ 5,  6  ,7,  8 , 9], [10 ,11 ,12 ,13 ,14], [15 ,16, 17 ,18, 19]]

at = [[] for i in range(2)]
org_1 = at

for i in range(0,4):  
  if i == 0 or i == 1:
    for j in range(0,5):
        org_1[0].append(org[i][j])
  else:
    for j in range(0,5):
        org_1[1].append(org[i][j])
print(org_1)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]


# squeeze
* 차원을 압축하는 함수(expand의 반대)
* 크기가 1인 차원만 제거하는 함수

In [8]:
import numpy as np
x = np.array([[[0], [1], [2]]])
x.shape
np.squeeze(x).shape

(3,)

In [11]:
np.squeeze(x, axis = 0)

array([[0],
       [1],
       [2]])

# expand_dims 
* 차원을 확장해주는 함수

In [65]:
import numpy as np
x = np.array([3,4])
x.shape

(2,)

In [70]:
y = np.expand_dims(x, axis = 1)
y.shape

(2, 1)

In [72]:
# 튜플을 사용하여 2개의 축에 차원을 한꺼번에 추가
y = np.expand_dims(x, axis = (0,1))
y.shape

(1, 1, 2)

In [75]:
# 1열, 2개가 하나씩
y = np.expand_dims(x, axis = (0,2))
print(y)
print(y.shape)

[[[3]
  [4]]]
(1, 2, 1)
